########~~~~-- Stages --~~~~########

stages:
  - secure
  - test
  - update
  - build
  - deploy

########~~~~-- Variables & defaults --~~~~########

variables:
  IMAGE: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:lts-jod"
  SCRIPT_TO_INSTALL_DEPS: "apt-get update && apt-get install -y git bash curl jq && npm install -g npm@latest && npm ci"

default:
  image: $IMAGE
  interruptible: true

########~~~~-- Workflows --~~~~########

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_PIPELINE_SOURCE == 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

########~~~~-- Includes --~~~~########

include:
  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/secret-finder/secret-finder@main"
    inputs:
      job_name: "find_secrets"
      stage_config: "secure"

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "format"
      stage_config: ".pre"
      branch_name: "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
      command: "npm ci && npm run clean"
      commit_message: "🎨 Format code automatically"
      image: "$IMAGE"
      script_to_install_deps: "$SCRIPT_TO_INSTALL_DEPS"
      consecutive_command_commits_allowed: false

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/command-runner/command-runner@main"
    inputs:
      job_name: "update"
      stage_config: "update"
      branch_name: "chore/update-dependencies"
      command: "npm run update-dependencies && npm run up-patch"
      commit_message: "⚙️ Update dependencies automatically"
      image: "$IMAGE"
      script_to_install_deps: "$SCRIPT_TO_INSTALL_DEPS"
      consecutive_command_commits_allowed: true

  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/docker-publisher/docker-publisher@main"
    inputs:
      job_name: "publish_to_docker"
      stage_config: "deploy"
      image_name: "beavuck/time"
      publish_to_dockerhub: true

find_secrets:
  rules: 
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

update:
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_UPDATE == 'true'"

format:
  rules: 
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

publish_to_docker:
  rules:
    - if: "$CI_COMMIT_TAG"
      when: manual

########~~~~-- Jobs --~~~~########

run_integration_tests:
  stage: test
  variables:
    API_PORT: 3000
    HOST_URL: http://localhost:3000
    TRUSTED_ORIGINS: http://localhost:8477
  before_script:
    - npm install -g npm@latest
    - npm ci
    - npm run build
    - npm start & sleep 10
  script: npm run run-integration-tests
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: find_secrets
      optional: true

coverage:
  stage: test
  artifacts:
    paths: [coverage/lcov.info]
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  before_script: npm install -g npm@latest && npm ci
  script: npm run test
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
    - if: "$CI_COMMIT_TAG"
  needs:
    - job: find_secrets
      optional: true

analyze:
  stage: test
  image:
    name: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/sonarsource/sonar-scanner-cli:latest"
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths: [.sonar/cache]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: 0 # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    - git config --global --add safe.directory "/builds/$CI_PROJECT_PATH"
    - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then PROJECT_VERSION=$LATEST_TAG; else PROJECT_VERSION=$LATEST_TAG-$CI_MERGE_REQUEST_ID; fi
    - sonar-scanner -Dsonar.projectVersion=$PROJECT_VERSION
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
  needs:
    - job: find_secrets
      optional: true
    - job: coverage
      artifacts: true

publish_to_npm:
  stage: deploy
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  script: npm publish --access public
  rules:
    - if: "$CI_COMMIT_TAG"
      when: manual