stages:
  - Test
  - Publish
  - Update dependencies

variables:
  DOCKER_IMAGE_NAME: 'beavuck/time'

test:
  image: node:22
  stage: Test
  script:
    - npm ci
    - npm test
  allow_failure: false
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  when: always

publish:
  image: docker:latest
  stage: Publish
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_WRITE_TOKEN"
    # push latest tag
    - docker build -t $DOCKER_IMAGE_NAME:latest .
    - docker push $DOCKER_IMAGE_NAME:latest
    # also push current tag
    - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  needs:
    - job: test
      artifacts: true

update_dependencies:
  image: node:22
  stage: Update dependencies
  variables:
    BRANCH_NAME: chore/update-dependencies
    COMMIT_MESSAGE: '⚙️ Update dependencies automatically'
    COMMAND: |
      npm ci && \
      ncu --format group && \
      ncu -u && \
      npm install && \
      npm prune && \
      npm audit fix && \
      npm run up-patch
    TMP_SCRIPTS_DIR: /tmp/scripts
  before_script:
    - apt-get update && apt-get install -y bash curl jq
  script:
    - mkdir -p $TMP_SCRIPTS_DIR
    - git clone https://gitlab-ci-token:$GITLAB_TOKEN@$GITLAB_HOST/beavuck-services/scripts/command-runner-and-mr-creator.git $TMP_SCRIPTS_DIR
    - cp $TMP_SCRIPTS_DIR/run_command_and_create_mr.sh .
    - chmod +x run_command_and_create_mr.sh
    - /bin/bash ./run_command_and_create_mr.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
