########~~~~-- Stages --~~~~########

stages:
  - secure
  - test
  - update
  - build
  - deploy

########~~~~-- Variables & defaults --~~~~########

default:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:lts-jod

########~~~~-- Workflows --~~~~########

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_PIPELINE_SOURCE == 'schedule'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

########~~~~-- Includes --~~~~########

include:
  - component: "$CI_SERVER_FQDN/beavuck-services/ci-cd-catalog/docker-publisher/docker-publisher@main"
    inputs:
      image_name: "beavuck/time"
      stage_config: "deploy"
      publish_to_dockerhub: true
      rules_config:
        - if: "$CI_COMMIT_TAG"
          when: manual

########~~~~-- Jobs --~~~~########

format:
  stage: .pre
  interruptible: true
  variables:
    BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    COMMIT_MESSAGE: "🎨 Format code automatically"
    COMMAND: npm run clean
    TMP_SCRIPTS_DIR: /tmp/ci-scripts
  before_script:
    - apt-get update && apt-get install -y bash curl jq
    - npm install -g npm@latest
    - npm ci
  script:
    - git fetch origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME)
    - if [[ "$LATEST_COMMIT_MESSAGE" == "$COMMIT_MESSAGE" ]]; then echo "Previous commit $LATEST_COMMIT_MESSAGE was a format job. Skipping format job now."; exit 0; fi
    - mkdir -p $TMP_SCRIPTS_DIR
    - git clone https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/beavuck-services/scripts/command-runner-and-mr-creator.git $TMP_SCRIPTS_DIR
    - cp $TMP_SCRIPTS_DIR/run_command_and_create_mr.sh .
    - chmod +x run_command_and_create_mr.sh
    - /bin/bash ./run_command_and_create_mr.sh
  rules: [if: "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH"]

find_secrets:
  stage: secure
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/gitguardian/ggshield:latest
  interruptible: true
  script: ggshield secret scan ci
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

run_integration_tests:
  stage: test
  interruptible: true
  variables:
    API_PORT: 9124
    HOST_URL: http://localhost:9124
    TRUSTED_ORIGINS: http://localhost:8477
  before_script:
    - npm install -g npm@latest
    - npm ci
    - npm run build
    - npm start & sleep 10
  script: npm run run-integration-tests
  rules: [if: "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG"]

run_unit_tests_then_analyze:
  stage: test
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  interruptible: true
  cache:
    key: "${CI_JOB_NAME}"
    paths: [.sonar/cache]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: 0 # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    - git config --global --add safe.directory /builds/beavuck-services/time
    - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then PROJECT_VERSION=$LATEST_TAG; else PROJECT_VERSION=$LATEST_TAG-$CI_MERGE_REQUEST_ID; fi
    - npm ci && npm test
    - sonar-scanner -Dsonar.projectVersion=$PROJECT_VERSION
  rules: [if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH"]

update_dependencies:
  stage: update
  interruptible: true
  variables:
    BRANCH_NAME: chore/update-dependencies
    COMMIT_MESSAGE: "⚙️ Update dependencies automatically"
    COMMAND: npm run update-dependencies && npm run up-patch
    TMP_SCRIPTS_DIR: /tmp/scripts
  before_script:
    - apt-get update && apt-get install -y bash curl jq
    - npm install -g npm@latest
    - npm ci
  script:
    - mkdir -p $TMP_SCRIPTS_DIR
    - git clone https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/beavuck-services/scripts/command-runner-and-mr-creator.git $TMP_SCRIPTS_DIR
    - cp $TMP_SCRIPTS_DIR/run_command_and_create_mr.sh .
    - chmod +x run_command_and_create_mr.sh
    - /bin/bash ./run_command_and_create_mr.sh
  rules: [if: "$CI_PIPELINE_SOURCE == 'schedule' && $IS_UPDATE == 'true'"]

describe_and_review:
  stage: .post
  image:
    name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/codiumai/pr-agent:latest
    entrypoint: [""]
  interruptible: true
  script:
    - if [[ "$CI_MERGE_REQUEST_LABELS" =~ (auto-generated|skip\ auto-review) ]]; then echo "Because of the labels of this MR, no AI review"; exit 0; fi
    - cd /app
    - echo "Creating code review..."
    - export gitlab__url=$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN
    - export config__git_provider="gitlab"
    - export gitlab__PERSONAL_ACCESS_TOKEN=$PR_AGENT_TOKEN
    - export openai__key=$OPENAI_API_KEY
    - python -m pr_agent.cli --pr_url="${MR_URL}" describe
    - python -m pr_agent.cli --pr_url="${MR_URL}" review
  rules:
    - if: "$CI_MERGE_REQUEST_LABELS =~ /auto-review/"
      needs: [run_unit_tests_then_analyze]
      when: on_success
    - if: "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH"
      needs: [run_unit_tests_then_analyze]
      when: manual
  allow_failure: true
