openapi: 3.0.0
info:
  title: Beavuck Time
  version: 1.0.0
  description: A simple microservice to get the current time in ISO format in UTC timezone.
servers:
  - url: http://127.0.0.1:3000
    description: Local server
paths:
  /now:
    get:
      summary: Get the current time in ISO format
      description: Returns the current time in ISO format, in UTC timezone.
      responses:
        '200':
          description: A JSON object containing the current date and time
          content:
            application/json:
              schema:
                type: object
                properties:
                  now:
                    type: string
                    format: date-time
                    example: "2024-06-14T18:25:46.835Z"
        '403':
          description: Forbidden. Invalid API key.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: time-api-key
security:
  - ApiKeyAuth: []
