sonar.projectKey=beavuck-services_time
sonar.organization=beavuck-services
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/coverage/**, **/build/**, **/api-tests/**, *package*.json, src/routes/routes.ts
sonar.coverage.exclusions=src/__tests__/middlewares/corsMiddleware.test.ts, src/__tests__/utils/stringUtils.test.ts, src/__tests__/utils/urlUtil.test.ts, src/__tests__/middlewares/errorHandler.test.ts, src/__tests__/config/corsOptions.test.ts, src/__tests__/api.test.ts, src/config/logger.ts, src/server.ts, src/middlewares/rateLimiter.ts, src/routes/routes.ts
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.coverage.inclusions=src/**/*.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
