sonar.projectKey=beavuck-services_time
sonar.organization=beavuck-services
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/coverage/**, **/dist/**, **/build/**, **/api-tests/**, *package*.json
sonar.coverage.exclusions=**/_tests_/**/*.*, src/config/logger.ts, src/server.ts, src/middlewares/rateLimiter.ts
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.coverage.inclusions=src/**/*.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
