sonar.projectKey=beavuck-services_time
sonar.organization=beavuck-services
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/api-tests/**,*package*.json
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.coverage.inclusions=src/utils/**,src/services/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
